### ISSUE TITLE
Returns packages that don't satisfy search criteria

### ISSUE THREAD

**Issue by yurivict** [repology/repology#655] opened 2018-07-10 04:37 UTC
This query
https://repology.org/metapackages/?search=&maintainer=yuri%40freebsd.org&category=&inrepo=freebsd&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on
should return all outdated FreeBSD packages maintained by me.

It returns python:pycryptodome which is outdated on FreeBSD but isn't maintained by me.

**Comment by AMDmi3** [comment] 2018-07-12 23:47
True, because repository and maintainer conditions are checked independently, so it's shown because you are still a maintainer in dports. This specific problem will go away as soon as dports are updated, to properly fix it some database changes would be required.

**Comment by mgorny** [comment] 2019-09-17 12:04
Bump. I'm also having major problems due to this bug. It seems that Funtoo (a Gentoo fork) includes a lot of Gentoo packages with outdated maintainer information. Then, e.g. when I'm searching for Gentoo packages maintained by `proxy-maint@gentoo.org` I'm getting a lot of results for packages that were maintained by us in the past.

**Comment by AMDmi3** [comment] 2019-09-30 14:23
I guess I have to force this, as there are repeated reports from at least Gentoo maintainers affected by this issue.

A short explanation of the problem and why it's not fixed yet. The problem is that *In repo* and *Maintainer* conditions in the project search are checked independently, so if you try to list packages maintainer by _foo@gentoo.org_ in _Gentoo_ it lists projects with have packages maintained by _foo@gentoo.org_ AND packages in _Gentoo_, while it should list projects with packages in _Gentoo_ AND maintained by _foo@gentoo.org_ at the same time.

Fixing this is not quite straightforward due to how Repology database is designed and may make the query too slow and/or require additional tables with aggregate information which would slow down the update and eay the diskspace. So I've postponed this until long planned update process refactoring.

Since latter is unlikely to be ready soon, I'm starting to work on fixing this with the current codebase, even if there are (tolerable) drawbacks.

**Comment by AMDmi3** [comment] 2019-09-30 14:38
Btw, examples of this behaviour would be helpful. I have one affecting myself with FreeBSD/DPorts, but it may go away as soon as DPorts are updated.

**Comment by mgorny** [comment] 2019-09-30 15:53
Example: https://repology.org/projects/?inrepo=gentoo&maintainer=proxy-maint%40gentoo.org

The first package on the list, 389-ds-base is reported wrongly.

**Comment by AMDmi3** [comment] 2019-09-30 17:54
@mgorny, does this look like the corrent and comple list of projects which should not be shown by https://repology.org/projects/?inrepo=gentoo&maintainer=proxy-maint%40gentoo.org

- 389-ds-base
- ahoviewer
- aide
- argp-standalone
- atom
- cadaver
- calise
- capyt
- ccnet
- ck-sources
- corebird
- cursors:neutral
- dnrd
- dnsdist
- dwarf-fortress
- e-gtk-theme
- econnman
- edi
- efl
- eix
- electron
- enlightenment
- enlightenment-extra
- ephoto
- eselect-electron
- esptool
- etckeeper
- eventd
- evisum
- flacon
- ftl
- fwbuilder
- fwknop
- gexiv2
- global
- grafana
- imlib2
- imlib2-loaders
- imv
- installer
- kakoune
- katawa-shoujo
- kvirc
- libgaminggear
- libsearpc
- lilypond
- linuxdoc-tools
- lxd
- mattermost-desktop
- midisport-firmware
- motion
- mpv
- mpv-bash-completion
- neon
- numix-gtk-theme
- opusfile
- pdfjs
- pesign
- plan9port
- pms-practical-music-search
- pngquant
- po4a
- protobuf
- purple-hangouts
- python:ansicolor
- python:babelfish
- python:cjkwrap
- python:enzyme
- python:guessit
- python:line-profiler
- python:matplotlib2tikz
- python:nbval
- python:protobuf-python
- python:python-efl
- python:python-ly
- python:rebulk
- python:sphinxcontrib-github-alt
- python:texttable
- python:uvloop
- qt5ct
- roccat-tools
- rt-sources
- rtirq
- ruby:hashicorp-checkpoint
- sbcl
- scdoc
- seafile
- seafile-client
- serf
- shaderc
- sqlite3
- sstp-client
- subliminal
- svrcore
- sway
- syncplay
- terminology
- uchardet
- ulogd
- umurmur
- vagrant
- validns
- vcsi
- vim:rust-vim
- vint
- wlroots
- xkblayout-state
- zopfli

**Comment by mgorny** [comment] 2019-09-30 20:11
Hmm, it looks correct, except for `gevix2` that shouldn't be present. However, it was changed two days ago, so I suspect you may be using old data.

**Comment by AMDmi3** [comment] 2019-09-30 21:01
> so I suspect you may be using old data

That would be correct - I've checked against local instance with data some days old. Okay, so we have a solution, will deploy tomorrow.

**Closed** 2019-09-30 21:02 UTC
Labels: component:core, component:sql, type:bug

**Comment by AMDmi3** [comment] 2019-10-01 15:16
The fix is now live.

**Comment by mgorny** [comment] 2019-10-01 15:32
Thanks, it seems to work correctly.
