### ISSUE TITLE
Reconsider terrible policy of non-releases trumping real releases

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#313] opened 2017-09-02 13:15 UTC
There are several examples.  One longer discussion via individual reporting on **recode** said to open issue here.

> The report is rejected because ignoring is meant for bogus versions, while 3.7beta2 is official and correct version

In the case of recode, there's nothing "official" about 3.7beta2.  It's a beta.  Releases >> release candidates >> beta >> alpha.

Just because a project is apparently abandoned after issuing a couple of beta versions doesn't make it okay to declare a "beta" version better than "release".

I realize that "ignore" was intended bad formats (or plain invalid) versions, but in general there badly needs to be "dev-release" type of ignore (touched on via issue #309) which does not trump a real release.  Put to a poll, there's no way the majority of professional users would agree that a "beta" release should be considered superior to the last true release.

While I show "recode" as an example, there are numerous cases like this in repology.  It's a systematic issue that needs to be handled in a much better fashion that currently handled.  The fact the project is "dead upstream" should have no standing, nor should it it's presence in unstable repos when the vast majority of professional repos are staying on the release INTENTIONALLY.

**Comment by AMDmi3** [comment] 2017-09-02 20:52
Duplicate of #309

**Closed** 2017-09-02 20:52 UTC

**Comment by jrmarino** [comment] 2017-09-02 20:58
There is some overlap, but it's not really a duplicate.
#309 covers dev versions in general (and the referenced #170 doesn't seem to even cover that but I'm trusting you when you say it does).

This covers the concept of priorities.  If a release is considered inferior to a beta *ever* then this issue is NOT a duplicate.  Plus you even said, "open an issue".

I'm very concerned about the strong opinion that betas are better than releases.  In order, I would like to see A) that never happen B) some kind of compromise where betas exists between "valid" and "ignore" or at least C) where this strange view is documented in a FAQ or something.
