### ISSUE TITLE
invalid 9999 version outdate marking

### ISSUE THREAD

**Issue by blshkv** [repology/repology#335] opened 2017-09-22 02:36 UTC
https://repology.org/metapackages/outdated-in-repo/gentoo_ovl_pentoo/

Hi, after a recent change the website started to display all our unique 9999 ebuilds as outdated. 

Could you have a look please?

**Comment by AMDmi3** [comment] 2017-09-22 19:27
Duplicate of #334

**Closed by AMDmi3** 2017-09-22 19:27 UTC
